# Generated by Django 5.0.1 on 2024-01-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0002_alter_recipes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='user',
        ),
    ]
